In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split

import pickle

In [2]:
df = pd.read_csv("../dataset/study_material_dataset.csv")
df.head()

,subject,user_level,difficulty,topic,youtube_link,tutorial_site_link
0,Python,Beginner,Easy,Python Fundamentals,https://www.youtube.com/@ProgrammingwithMosh,https://docs.python.org/3/
1,Python,Intermediate,Medium,Python Fundamentals,https://www.youtube.com/@ProgrammingwithMosh,https://docs.python.org/3/
2,Python,Advanced,Hard,Python Fundamentals,https://www.youtube.com/@ProgrammingwithMosh,https://docs.python.org/3/
3,SQL,Beginner,Easy,SQL Fundamentals,https://www.youtube.com/@freecodecamp,https://www.w3schools.com/sql/
4,SQL,Intermediate,Medium,SQL Fundamentals,https://www.youtube.com/@freecodecamp,https://www.w3schools.com/sql/

In [3]:
df.describe()

,subject,user_level,difficulty,topic,youtube_link,tutorial_site_link
count,144,144,144,144,144,144
unique,48,3,3,48,8,9
top,Python,Beginner,Easy,Python Fundamentals,https://www.youtube.com/@freecodecamp,https://www.geeksforgeeks.org/
freq,3,48,48,3,123,120

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   subject             144 non-null    object
 1   user_level          144 non-null    object
 2   difficulty          144 non-null    object
 3   topic               144 non-null    object
 4   youtube_link        144 non-null    object
 5   tutorial_site_link  144 non-null    object
dtypes: object(6)
memory usage: 6.9+ KB

In [5]:
le_subject = LabelEncoder()
le_user_level = LabelEncoder()
le_difficulty = LabelEncoder()
le_topic = LabelEncoder()

In [6]:
df['subject_enc'] = le_subject.fit_transform(df['subject'])
df['user_level_enc'] = le_user_level.fit_transform(df['user_level'])
df['difficulty_enc'] = le_difficulty.fit_transform(df['difficulty'])
df['topic_enc'] = le_topic.fit_transform(df['topic'])

In [7]:
df[['subject', 'subject_enc',
'user_level', 'user_level_enc',
'difficulty', 'difficulty_enc',
'topic', 'topic_enc']].head()

,subject,subject_enc,user_level,user_level_enc,difficulty,difficulty_enc,topic,topic_enc
0,Python,35,Beginner,1,Easy,0,Python Fundamentals,35
1,Python,35,Intermediate,2,Medium,2,Python Fundamentals,35
2,Python,35,Advanced,0,Hard,1,Python Fundamentals,35
3,SQL,38,Beginner,1,Easy,0,SQL Fundamentals,38
4,SQL,38,Intermediate,2,Medium,2,SQL Fundamentals,38

In [8]:
X = df[['subject_enc', 'user_level_enc', 'difficulty_enc', 'topic_enc']]

In [9]:
X_train, X_test = train_test_split(
X,
test_size=0.2,
random_state=42
)

In [10]:
knn = NearestNeighbors(
n_neighbors=5,
metric='euclidean'
)

In [11]:
knn.fit(X_train)

NearestNeighbors(metric='euclidean')

In [12]:
X_train

     subject_enc  user_level_enc  difficulty_enc  topic_enc
124           43               2               2         43
31             2               2               2          2
98            22               0               1         22
36            16               1               0         16
16             7               2               2          7
..           ...             ...             ...        ...
71            45               0               1         45
106           10               2               2         10
14             6               0               1          6
92             0               0               1          0
102           30               1               0         30

[115 rows x 4 columns]

In [13]:
X_test

     subject_enc  user_level_enc  difficulty_enc  topic_enc
117           39               1               0         39
19            13               2               2         13
82            19               2               2         19
97            22               2               2         22
56            23               0               1         23
12             6               1               0          6
132           18               1               0         18
65            47               0               1         47
66            21               1               0         21
18            13               1               0         13
51             5               1               0          5
78            44               1               0         44
94             3               2               2          3
133           18               2               2         18
100           15               2               2         15
64            47               2               2         47
27            14               1               0         14
69            45               1               0         45
125           43               0               1         43
73            17               2               2         17
11            24               0               1         24
119           39               0               1         39
110           42               0               1         42
113           28               0               1         28
55            23               2               2         23
45            12               1               0         12
9             24               1               0         24
4             38               2               2         38
26            46               0               1         46

In [14]:
sample_input = np.array([[
le_subject.transform(['Python'])[0],
le_user_level.transform(['Beginner'])[0],
le_difficulty.transform(['Easy'])[0],
le_topic.transform(['Python Basics'])[0]
]])

distances, indices = knn.kneighbors(sample_input)

df.iloc[indices[0]][[
'subject',
'user_level',
'difficulty',
'topic',
'youtube_link',
'tutorial_site_link'
]]

ValueError: y contains previously unseen labels: 'Python Basics'

In [ ]:
knn.fit(X)

In [ ]:
model_data = {
'knn_model': knn,
'dataset': df,
'subject_encoder': le_subject,
'user_level_encoder': le_user_level,
'difficulty_encoder': le_difficulty,
'topic_encoder': le_topic
}

with open("knn_model.pkl", "wb") as file:
    pickle.dump(model_data, file)